"use client";

import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { api } from "@/lib/api";
import { TempNumberOrder,TempNumberService,tempStatusTerminal } from "@/lib/temp-number";

export default function TempNumberOverview(){
  const[services,setServices]=useState<TempNumberService[]>([]);const[orders,setOrders]=useState<TempNumberOrder[]>([]);const[favorites,setFavorites]=useState<string[]>([]);const[query,setQuery]=useState("");const[loadingService,setLoadingService]=useState("");const[loadingOrder,setLoadingOrder]=useState<number|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");const requestKeys=useRef(new Map<string,string>());const pollIndex=useRef(0);
  const loadOrders=useCallback(async()=>setOrders((await api<{orders:TempNumberOrder[]}>("/api/temp-number/orders")).orders),[]);
  useEffect(()=>{Promise.all([api<{services:TempNumberService[]}>("/api/temp-number/services"),api<{orders:TempNumberOrder[]}>("/api/temp-number/orders"),api<{favorites:string[]}>("/api/temp-number/favorites")]).then(([catalog,history,saved])=>{setServices(catalog.services);setOrders(history.orders);setFavorites(saved.favorites)}).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load temporary numbers."))},[]);
  const visibleServices=useMemo(()=>{const needle=query.trim().toLowerCase();return services.filter(service=>!needle||service.service_name.toLowerCase().includes(needle)).sort((a,b)=>{const favoriteDifference=Number(favorites.includes(b.api_name))-Number(favorites.includes(a.api_name));return favoriteDifference||a.service_name.localeCompare(b.service_name)})},[services,favorites,query]);
  async function toggleFavorite(event:React.MouseEvent,service:TempNumberService){event.stopPropagation();setError("");try{const result=await api<{service:string;favorite:boolean}>(`/api/temp-number/favorites/${encodeURIComponent(service.api_name)}`,{method:"POST"});setFavorites(current=>result.favorite?[result.service,...current.filter(item=>item!==result.service)]:current.filter(item=>item!==result.service))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to update this favourite.")}}
  async function purchase(service:TempNumberService){if(service.stock<1||loadingService)return;setLoadingService(service.api_name);setError("");setMessage("");let requestKey=requestKeys.current.get(service.api_name);if(!requestKey){requestKey=crypto.randomUUID();requestKeys.current.set(service.api_name,requestKey)}try{const result=await api<{order:TempNumberOrder}>("/api/temp-number/orders",{method:"POST",body:JSON.stringify({service:service.api_name,idempotency_key:requestKey})});requestKeys.current.delete(service.api_name);setOrders(current=>[result.order,...current.filter(order=>order.id!==result.order.id)]);setServices(current=>current.map(item=>item.api_name===service.api_name?{...item,stock:Math.max(0,item.stock-1)}:item));setMessage(result.order.number?`${service.service_name} number purchased successfully.`:"Your number is being confirmed.");window.dispatchEvent(new CustomEvent("wallet-updated"))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to purchase this number.")}finally{setLoadingService("")}}
  const updateOrder=useCallback(async(order:TempNumberOrder,action:"status"|"cancel")=>{setLoadingOrder(order.id);setError("");try{const result=await api<{order:TempNumberOrder}>(`/api/temp-number/orders/${order.id}/${action}`,{method:"POST"});setOrders(current=>current.map(item=>item.id===order.id?result.order:item));if(result.order.refunded)window.dispatchEvent(new CustomEvent("wallet-updated"))}catch(reason){setError(reason instanceof Error?reason.message:"Unable to update this rental.")}finally{setLoadingOrder(null)}},[]);
  useEffect(()=>{const timer=window.setInterval(()=>{const active=orders.filter(order=>!tempStatusTerminal(order.status)&&Boolean(order.number));if(!active.length)return;const order=active[pollIndex.current%active.length];pollIndex.current+=1;void updateOrder(order,"status")},10000);return()=>window.clearInterval(timer)},[orders,updateOrder]);
  const recent=orders.filter(order=>["active","completed"].includes(order.status.toLowerCase())).slice(0,15);
  return <><div className="dash-heading temp-page-heading"><div><span className="dash-kicker">Temporary Numbers</span><h1>USA verification numbers</h1><p>Select a service to purchase a number instantly from your Naira wallet.</p></div></div>{error&&<div className="dash-alert error">{error}</div>}{message&&<div className="dash-alert success">{message}</div>}
    <div className="temp-tables-layout"><section className="dash-panel temp-table-panel"><div className="panel-head"><div><h2>Rent USA numbers</h2><p>Click a service row to rent its number immediately.</p></div></div><div className="temp-service-search"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search services..." aria-label="Search temporary number services"/></div><div className="dash-table-wrap temp-service-table-wrap"><table className="dash-table temp-service-table"><thead><tr><th>Service</th><th>Price</th><th aria-label="Favourite"/></tr></thead><tbody>{visibleServices.map(service=><tr key={service.api_name} className={service.stock>0?"is-buyable":"is-unavailable"} onClick={()=>void purchase(service)}><td><strong>{service.service_name}</strong>{service.stock<1&&<small>Out of stock</small>}</td><td><strong>₦{Number(service.price_ngn).toLocaleString("en-NG",{minimumFractionDigits:2})}</strong></td><td><button className={favorites.includes(service.api_name)?"temp-favorite active":"temp-favorite"} onClick={event=>void toggleFavorite(event,service)} aria-label={favorites.includes(service.api_name)?`Remove ${service.service_name} from favourites`:`Add ${service.service_name} to favourites`} title="Favourite"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg></button></td></tr>)}</tbody></table>{loadingService&&<div className="temp-purchase-overlay"><span className="temp-mini-spinner"/> Purchasing {services.find(item=>item.api_name===loadingService)?.service_name}...</div>}{!services.length&&!error&&<div className="table-loading"><span className="temp-mini-spinner"/> Loading services...</div>}{services.length>0&&!visibleServices.length&&<div className="table-loading">No services match your search.</div>}</div></section>
    <section className="dash-panel temp-table-panel"><div className="panel-head"><div><h2>Recent Rentals</h2><p>Active rentals and recently received codes.</p></div><button className="temp-refresh-all" onClick={()=>void loadOrders()}>Refresh</button></div><div className="dash-table-wrap"><table className="dash-table temp-rentals-table"><thead><tr><th>Flag</th><th>Number</th><th>Service</th><th>Code</th><th>Status</th></tr></thead><tbody>{recent.map(order=><tr key={order.id}><td><span className="temp-flag" aria-label="United States">🇺🇸</span></td><td><strong>{order.number||"Confirming..."}</strong><small>Order #{order.id}</small></td><td><strong>{order.service_name}</strong><small>₦{Number(order.price_ngn).toLocaleString("en-NG",{minimumFractionDigits:2})}</small></td><td>{order.code?<strong className="temp-code-text">{order.code}</strong>:<span className="temp-waiting"><i className="temp-mini-spinner"/> Waiting</span>}</td><td><div className="temp-status-action"><span className={`status-pill ${order.status.toLowerCase().replaceAll(" ","-")}`}>{order.status}</span>{order.status.toLowerCase()==="active"&&<button disabled={loadingOrder===order.id} onClick={()=>void updateOrder(order,"cancel")}>{loadingOrder===order.id?"Cancelling...":"Cancel"}</button>}</div></td></tr>)}</tbody></table>{!recent.length&&<div className="dash-empty"><span>☎</span><h3>No recent rentals</h3><p>Choose a service to rent your first number.</p></div>}</div></section></div>
  </>;
}
