"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";

type Rental={id:number;user_id:number;provider_rental_id:number|null;provider_request_id:string|null;service:string;service_name:string;country:string;number:string|null;code:string|null;status:string;wholesale_price:string;retail_price:string;currency:string;end_time:string|null;customer_refunded:number;last_error:string|null;created_at:string;updated_at:string;user_name:string;user_email:string};
const money=(value:string|number)=>`₦${Math.ceil(Number(value)).toLocaleString("en-NG")}`;
const terminal=(status:string)=>["completed","cancelled","canceled","expired","failed"].includes(status.toLowerCase());

export default function AdminTempNumbers(){
  const[rows,setRows]=useState<Rental[]>([]);const[query,setQuery]=useState("");const[status,setStatus]=useState("");const[service,setService]=useState("");const[country,setCountry]=useState("");const[refund,setRefund]=useState("");const[from,setFrom]=useState("");const[to,setTo]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<number|null>(null);const[error,setError]=useState("");const[message,setMessage]=useState("");
  const load=useCallback(()=>{setLoading(true);setError("");return api<{rentals:Rental[]}>("/api/admin/temp-numbers").then(result=>setRows(result.rentals)).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load temporary number rentals.")).finally(()=>setLoading(false))},[]);
  useEffect(()=>{void load()},[load]);
  const statuses=useMemo(()=>[...new Set(rows.map(row=>row.status))].sort(),[rows]);
  const shown=useMemo(()=>rows.filter(row=>{const needle=query.toLowerCase();const created=row.created_at.slice(0,10);return(!needle||`${row.id} ${row.provider_rental_id??""} ${row.provider_request_id??""} ${row.country} ${row.service} ${row.user_name} ${row.user_email} ${row.service_name} ${row.number??""} ${row.code??""}`.toLowerCase().includes(needle))&&(!service||row.service===service)&&(!country||row.country===country)&&(!refund||(refund==="yes")===Boolean(row.customer_refunded))&&(!status||row.status===status)&&(!from||created>=from)&&(!to||created<=to)}),[rows,query,status,service,country,refund,from,to]);
  const active=rows.filter(row=>!terminal(row.status)).length;const completed=rows.filter(row=>row.status.toLowerCase()==="completed").length;const refunded=rows.filter(row=>Boolean(row.customer_refunded)).length;const sales=rows.filter(row=>!Boolean(row.customer_refunded)&&row.status.toLowerCase()!=="failed").reduce((sum,row)=>sum+Number(row.retail_price),0);
  async function action(row:Rental,type:"status"|"cancel"){
    if(type==="cancel"&&!window.confirm(`Cancel ${row.service_name} rental #${row.id}? A confirmed cancellation without an SMS will refund the customer.`))return;
    setBusy(row.id);setError("");setMessage("");
    try{const result=await api<{message:string}>(`/api/admin/temp-numbers/${row.id}/${type}`,{method:"POST"});setMessage(result.message);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Unable to update this rental.")}finally{setBusy(null)}
  }
  return <><div className="dash-heading"><div><span className="dash-kicker">Temporary Numbers</span><h1>Number rentals</h1><p>Monitor customer rentals, SMS delivery, provider status, pricing and refunds.</p></div><button className="button button-secondary" onClick={()=>void load()}>↻ Refresh all</button></div>
    {message&&<div className="dash-alert success">{message}</div>}{error&&<div className="dash-alert error">{error}</div>}
    <div className="admin-stat-grid admin-temp-stats">{[["All rentals",rows.length],["Active",active],["Completed",completed],["Refunded",refunded],["Net sales",money(sales)]].map(([label,value])=><article key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</div>
    <section className="dash-panel"><div className="table-toolbar admin-filters"><div className="dash-search">⌕ <input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search rentals" placeholder="Customer, rental ID, service, number or code..."/></div><select aria-label="Rental status" value={status} onChange={event=>setStatus(event.target.value)}><option value="">All statuses</option>{statuses.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Service" value={service} onChange={event=>setService(event.target.value)}><option value="">All services</option>{[...new Map(rows.map(row=>[row.service,row.service_name])).entries()].sort((a,b)=>a[1].localeCompare(b[1])).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="Country" value={country} onChange={event=>setCountry(event.target.value)}><option value="">All countries</option>{[...new Set(rows.map(row=>row.country))].sort().map(value=><option key={value}>{value}</option>)}</select><select aria-label="Refund status" value={refund} onChange={event=>setRefund(event.target.value)}><option value="">All refund states</option><option value="yes">Refunded</option><option value="no">Not refunded</option></select><label>From<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button type="button" onClick={()=>{setQuery("");setStatus("");setService("");setCountry("");setRefund("");setFrom("");setTo("")}}>Clear</button><span className="admin-count">{shown.length} records</span></div>
      {loading?<div className="table-loading">Loading rentals...</div>:<div className="dash-table-wrap"><table className="dash-table admin-table admin-temp-table"><thead><tr><th>Rental</th><th>Customer</th><th>Service</th><th>Number / code</th><th>Pricing</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{shown.map(row=><tr key={row.id}><td><strong>#{row.id}</strong><small>{row.provider_rental_id?`Provider #${row.provider_rental_id}`:row.provider_request_id?`Request ${row.provider_request_id}`:"Awaiting provider"}</small></td><td><strong>{row.user_name}</strong><small>{row.user_email}</small></td><td><strong>{row.service_name}</strong><small>{row.service} · {row.country}</small></td><td><strong>{row.number||"Not assigned"}</strong><small className={row.code?"temp-code-text":""}>{row.code?`Code: ${row.code}`:"No SMS code"}</small></td><td><strong>{money(row.retail_price)}</strong><small>Cost {money(row.wholesale_price)}</small></td><td><span className={`wallet-status wallet-status-${row.status.toLowerCase().replaceAll(" ","-")}`}>{row.status}</span>{Boolean(row.customer_refunded)&&<small className="temp-refunded">Customer refunded</small>}{row.last_error&&<small title={row.last_error}>Provider error</small>}</td><td>{new Date(row.created_at).toLocaleDateString()}<small>{row.end_time?`Ends ${new Date(row.end_time).toLocaleString()}`:"No expiry"}</small></td><td><div className="row-actions"><button disabled={busy===row.id||!row.provider_rental_id||terminal(row.status)} onClick={()=>void action(row,"status")}>{busy===row.id?"Working...":"Refresh"}</button><button className="admin-temp-cancel" disabled={busy===row.id||!row.provider_rental_id||terminal(row.status)} onClick={()=>void action(row,"cancel")}>Cancel</button></div></td></tr>)}</tbody></table>{!shown.length&&<div className="table-loading">No rentals found.</div>}</div>}
    </section></>;
}
